###

GET http://localhost:3007/api/jornadas/ed/sub23 HTTP/1.1

###

POST http://localhost:3007/api/admin/newTorneo HTTP/1.1
Content-Type: application/json

{
    "Liga" : "Carlos corriendo de Diego",
    "Categoria" : "Carlos corriendo de Diego",
    "Torneo" : "Carlos corriendo de Diego"

}
###
POST http://localhost:3007/api/admin/Jugadores HTTP/1.1
Content-Type: application/json

{
    "Id" : 1234,
    "Nombre" : "Jorge Barraza",
    "Curp" : "Nare920824"

}